---
- name: "Display GitHub link"
  debug:
    msg: "Find me on github https://github.com/rgee0/openfaas-DO"
    
- name: "Create DO droplet"
  digital_ocean:
      state: present
      command: droplet
      name: OpenFaaS
      api_token: "{{ token }}"
      ssh_key_ids: "{{ sshid }}"
      size_id: "{{ size_slug }}"
      region_id: "{{ region }}"
      image_id: "{{ image }}"
      wait_timeout: 500
  register: OFDroplet

- name: Set droplet_ip variable
  set_fact:
     droplet_ip: "{{ OFDroplet.droplet.ip_address }}"
  no_log: True 

- name: Add host to the inventory
  add_host: 
      name: "{{ OFDroplet.droplet.ip_address }}"
  no_log: True 

- name: Wait for the instance to boot by checking the ssh port
  wait_for: 
    host: "{{ OFDroplet.droplet.ip_address }}" 
    port: 22 
    delay: 30 
    timeout: 120 
    state: started
