---
- name: "Create DO droplet"
  digital_ocean:
      state: present
      command: droplet
      name: OpenFaaS
      api_token: "{{ token }}"
      ssh_key_ids: "{{ sshid }}"
      size_id: "{{ size_slug }}"
      region_id: "{{ region }}"
      image_id: "{{ image }}"
      wait_timeout: 500
  register: OFDroplet

- set_fact:
     droplet_ip: "{{ OFDroplet.droplet.ip_address }}"
  no_log: True 

- add_host: 
      name: "{{ OFDroplet.droplet.ip_address }}"
  no_log: True 

- name: Wait for the instances to boot by checking the ssh port
  wait_for: host="{{ OFDroplet.droplet.ip_address }}" port=22 delay=30 timeout=60 state=started
