---
- name: Look up latest openfaas release
  uri:
    url: https://api.github.com/repos/openfaas/faas/releases/latest
    return_content: yes
  register: OFVersion

- name: Install Docker
  raw: curl -sSL get.docker.com | sh
      
- name: Init docker swarm
  raw: docker swarm init --advertise-addr {{ hostvars.localhost.droplet_ip }}

- name: Checkout the lastest OpenFaaS release
  git:
    repo: 'https://github.com/openfaas/faas.git'
    dest: ~/faas
    version: "{{ OFVersion.json.tag_name }}"

- name: Deploy OpenFaas stack
  shell: ~/faas/deploy_stack.sh
  args:
    chdir: ~/faas/